{
 "title": "dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Tiler Utilization %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tiler_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Renderer Utilization %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "renderer_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Device Utilization %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "device_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Alloc system memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "alloc_system_memory", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "In use system memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "in_use_system_memory", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "TiledSceneBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "tiled_scene_bytes", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Allocated PB Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "allocated_pb_size", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "recoveryCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "recovery_count", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "SplitSceneCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "split_scene_count", "legendFormat": "{{name}}" }
   ]
  }
 ]
}